#index:
#    path: /
#    controller: App\Controller\DefaultController::index

list:
    path: /
    controller: App\Controller\MagicController::list


play:
    path: /play
    controller: App\Controller\MagicController::play
